### ISSUE TITLE
how to fix error [bug]

### ISSUE THREAD

**Issue by liguanghe** [Edgenesis/shifu-plugin-for-chatgpt#2]
hi,great job.
i cloned it to my computer, and after i ran, it shows:
/Users/liguanghe/.npm/_npx/a67ddc7a09eebd4d/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:319
const error = new Error(message);
^

Error: Network Error
at createError (/Users/liguanghe/.npm/_npx/a67ddc7a09eebd4d/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:319:19)
at getResponse (/Users/liguanghe/.npm/_npx/a67ddc7a09eebd4d/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:196:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async fetchAdapter (/Users/liguanghe/.npm/_npx/a67ddc7a09eebd4d/node_modules/langchain/dist/util/axios-fetch-adapter.cjs:172:18) {
config: {
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
},

my version:
Node.js v20.1.0
Mac os

so what could i do ~?
thanks

**Comment by tomqin93** [comment]
hi @liguanghe , pretty sure you had the wrong repo, going to close this issue
